name = "cinawalletkit-with-remix"
compatibility_date = "2026-06-17"
compatibility_flags = ["nodejs_compat"]
main = "worker/polyfill.ts"
workers_dev = true

routes = [{ pattern = "remix.cinacoin.com/*", zone_name = "cinacoin.com" }]

[assets]
directory = "public"
binding = "ASSETS"
run_worker_first = true

[observability]
enabled = true
